spring.application.name=api-gateway
server.port=9000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

# Removed invalid property 'eureka.client.use-registration-client'
#eureka.client.webclient.enabled=false


# Habilitar la obtención del registro y el registro en Eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Configuración de salud e intervalos
#eureka.client.healthcheck.enabled=true
#eureka.instance.lease-renewal-interval-in-seconds=30
#eureka.instance.lease-expiration-duration-in-seconds=90

# Configuración del cliente HTTP (importante para el error de redirect)
eureka.client.webclient.enabled=true

#User service routes
spring.cloud.gateway.mvc.routes[0].id=usuarios-service
spring.cloud.gateway.mvc.routes[0].uri=lb://usuarios-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/usuarios/**,/auth/**

#Order service routes
spring.cloud.gateway.mvc.routes[1].id=ordenes-service
spring.cloud.gateway.mvc.routes[1].uri=lb://ordenes-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/ordenes/**

#Product service routes
spring.cloud.gateway.mvc.routes[2].id=productos-service
spring.cloud.gateway.mvc.routes[2].uri=lb://productos-service
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/productos/**,/categorias/**

#Entregas service routes
spring.cloud.gateway.mvc.routes[3].id=entregas-service
spring.cloud.gateway.mvc.routes[3].uri=lb://entregas-service
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/entregas/**


#Log
#logging.level.root==info
#logging.level.org.springframework.cloud.gateway=debug
#logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=debug

#Tracing
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0

logging.pattern.level= %5p [${spring.application.name}, %X{traceId:-},%X{spanId:-}]
