name: Deploy Users Microservice

on:
  push:
    branches: [ "feat/usuarios" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests -f usuarios-service/pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/usuarios-service:latest -f usuarios-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/usuarios-service:latest

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project helpful-spider-445913-v9

      - name: Configure Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
          kubectl get nodes  # Prueba la conexión

      - name: Deploy to Kubernetes
        run: |
          sed -i "s|\$DOCKER_USERNAME|${DOCKER_USERNAME}|g" usuarios-service/kubernetes/deployment.yml
          kubectl apply -f usuarios-service/kubernetes/deployment.yml
          kubectl apply -f usuarios-service/kubernetes/service.yml