name: Deploy Users Microservice

on:
  push:
    branches:
      - develop
      - test-workflow
  pull_request:
    branches: 
      - develop
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Tests with Maven
        run: mvn test -f sistema-gestion-ordenes/backend/usuarios-service/pom.xml

      - name: Build with Maven
        run: mvn clean package -f sistema-gestion-ordenes/backend/usuarios-service/pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/usuarios-service:latest -f sistema-gestion-ordenes/backend/usuarios-service/Dockerfile sistema-gestion-ordenes/backend/usuarios-service/
          docker push ${{ secrets.DOCKER_USERNAME }}/usuarios-service:latest

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
          echo "Instalando Google Cloud SDK..."
          sudo apt-get update -y
          sudo apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update -y
          sudo apt-get install -y google-cloud-sdk
          echo "Instalando plugin de autenticación..."
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin     
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> ~/.bashrc
          gke-gcloud-auth-plugin --version
          kubectl version --client
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
            sed -i "s|\$DOCKER_USERNAME|${DOCKER_USERNAME}|g" sistema-gestion-ordenes/backend/usuarios-service/kubernetes/deployment.yml
            cat sistema-gestion-ordenes/backend/usuarios-service/kubernetes/deployment.yml | grep "image:"
            kubectl apply -f sistema-gestion-ordenes/backend/usuarios-service/kubernetes/deployment.yml
            kubectl apply -f sistema-gestion-ordenes/backend/usuarios-service/kubernetes/service.yml
            kubectl get pods -w